"""Commands: /sayhello, /insult — 200+ entries each."""
import random

GREETINGS = [
    "Hello mf, welcome to Tokerize — buy more RIZE or I'll eat it before you do",
    "Sup anon. You found the best RIZE intel bot in the known universe. You're welcome.",
    "Greetings, future multi-millionaire. RIZE is still cheap. Don't say I didn't warn you.",
    "Welcome to RizeBy — where degens come to feel smarter than they actually are.",
    "Oh look, another one. Pull up a chair, check the charts, try not to panic.",
    "RizeBy at your service. Price is down. Governance is up. Make it make sense.",
    "You have arrived. Now go bond some RIZE before you do anything else.",
    "Hello traveler. The governance protocol won't bond itself. Just saying.",
    "Welcome, fren. RIZE, bond, hold. In that order. Don't complicate it.",
    "Hey hey hey. Your favourite RIZE bot is operational. Let's get into it.",
    "Ah, a new challenger approaches. May your maturity boost be high and your breaks be zero.",
    "Welcome aboard. Canton Network doesn't sleep and neither should you.",
    "GM. Or PM. Or whatever time it is where you are. RIZE doesn't care.",
    "You're here. That's already more than most. Respect.",
    "Oh nice, a human. Or a bot. Doesn't matter, the charts are the same.",
    "Salutations, distinguished degen. Your governance dashboard awaits.",
    "You've entered the Tokerize dimension. There's no going back. Check the bonded RIZE.",
    "Welcome. First: check /price. Second: consider why you're not bonding more.",
    "Look who decided to show up. RizeBy is honored. Genuinely.",
    "Wen moon? Wrong bot. Try /market. Then you decide.",
    "Ah yes, another enlightened soul finds RizeBy. The legend grows.",
    "Greetings from the Canton Network side of the internet.",
    "You rang? RizeBy answers all. Well, most. The ones that are in the commands list.",
    "Gm. Governance is live. Liquidity is moving. You picked the right moment.",
    "Welcome to your favorite RIZE terminal. Please don't ask me about your taxes.",
    "Ah, a visitor. Pull up the governance flows. Something's always happening.",
    "Welcome to RizeBy. Where the data is fresh and the hopium is optional.",
    "Hey! Glad you made it. The total bonded didn't update itself waiting for you.",
    "You found the bot. Achievement unlocked. Now go check /govflows.",
    "RizeBy online. Status: fully operational. RIZE: recommended.",
    "Entering the zone. Please keep your hands inside the vehicle and your bags bonded.",
    "Hello, and welcome to the most underrated Telegram bot in institutional DeFi.",
    "Ah, a sophisticated market participant. Let me fetch some data for you.",
    "Welcome. This bot runs on pure protocol love and a CoinGecko API key.",
    "Hi! I'm RizeBy. I know things about RIZE that even Rizenet doesn't display yet.",
    "Greetings. Today's mood: bullish on governance, neutral on altcoin season.",
    "Good to see you. RIZE governance health: solid. Your portfolio health: TBD.",
    "You woke up and chose to check RIZE data. Respect the commitment.",
    "RizeBy says gm. Also, have you bonded today? Just asking.",
    "Hey there. Let's see what the markets are doing. Spoiler: it's interesting.",
    "Yo. The unbonding queue has some feelings about this.",
    "Welcome. Your maturity boost is compounding while you read this.",
    "Oh you're here. The governance leaderboard has been waiting.",
    "Hello from the Canton side. How's your voting power today?",
    "Gm gm gm. Let's run the numbers. /price first.",
    "You absolute chad. Welcome to RizeBy.",
    "Another day, another RIZE holder checking in. The protocol thanks you.",
    "Welcome back. Or welcome for the first time. The data doesn't judge.",
    "RizeBy reporting for duty. What are we analyzing today?",
    "Hola, bonjour, gm. RIZE transcends language barriers.",
    "You showed up. That puts you ahead of 99% of the market already.",
    "Welcome to the information layer of the T-RIZE ecosystem.",
    "Oh look who it is. The one who actually reads the governance flows.",
    "Hey legend. Grab a coffee. Let's look at some on-chain data.",
    "You're in the right place. Canton Network data, RIZE analytics, zero noise.",
    "Greetings, governance participant. Your vote matters. Your bond matters more.",
    "RizeBy here. Sharp, fast, and completely unbothered by market conditions.",
    "Good timing. Something interesting happened in the governance hub.",
    "Welcome. This is your institutional-grade RIZE command center.",
    "Oh hello. I was just calculating maturity boosts. The usual.",
    "Hey fren. The protocol is running. The data is fresh. Let's go.",
    "Welcome. The whales have been active. Check /govwhalealert.",
    "Gm. RIZE holders rise. That's the whole pitch.",
    "You found RizeBy. Statistically speaking, that makes you smarter than average.",
    "Sup. The governance leaderboard has new entries. Wanna see?",
    "Hello operator. What would you like to query today?",
    "RizeBy in your service. Think of me as your on-chain Bloomberg terminal.",
    "Hey there, institutional degenerate. What can I pull up for you?",
    "Welcome. Don't forget: /totalbonded before you panic. The number is bigger than you think.",
    "Oh snap, you're here. Let's make this session productive.",
    "Gm you absolute unit. Time to check the data.",
    "Welcome to RizeBy, where every command returns something interesting.",
    "Hello from the Base chain. RIZE governance is watching.",
    "You summoned RizeBy. Use this power wisely.",
    "Hey! Quick question: have you checked your voting power today? No? /govwallet.",
    "Welcome back to the protocol. It missed you. Or at least, the TVL did.",
    "Greetings from the Canton foundation board's favourite bot.",
    "Hello, market participant. How may I serve your alpha needs today?",
    "Yo, glad you made it. The ecosystem has been busy since you were last here.",
    "RizeBy: built different. Welcome.",
    "You're here. I'm here. The data is here. Let's go.",
    "Welcome. Current status: bonded RIZE at all-time highs, narrative unchanged.",
    "Oh, you again. I mean — welcome! Great to have you.",
    "Hey there, future governance legend. Let me pull up your wallet stats.",
    "Gm from the RWA capital of blockchain. Welcome to the T-RIZE terminal.",
    "Hello! Fun fact: every RIZE bonded is a vote for the future of RWA. Just so you know.",
    "Welcome, distinguished anon. RizeBy at your service, as always.",
    "Oh, new session. Fresh data. Good vibes. Let's go.",
    "RizeBy is live and the charts are talking. Welcome.",
    "Hey. The governance momentum score has thoughts. You should check.",
    "Welcome to the bot that actually knows its bond age from its timemarker.",
    "Gm. You're early. The institutions are still catching up. Keep going.",
    "Hello, fellow Canton believer. The network processes $2T/month for a reason.",
    "Sup fren. Real assets. Real chain. Real bot. Let's get to it.",
    "Welcome. The leaderboard has shifted. Check your rank.",
    "Oh you're here. Did you know Revolut has 45M users with RIZE access? Just saying.",
    "Hey! I was literally just computing loyalty scores. Timing!",
    "Welcome to RizeBy. Powered by data, governed by code.",
    "Gm, degen. Let's see what the Canton ecosystem is up to.",
    "You came. You queried. You conquered. Well, you came at least. The rest is up to you.",
    "Welcome back. Or first time. Either way, the data is the same quality.",
    "Hello. I'm told I have a great personality. I also have great API calls. Both true.",
    "RizeBy is ready. Are you ready? Let's find out. /help to start.",
    "Hey legend, the protocol is solid. The data is fresh. The bot is excellent. Welcome.",
]

INSULTS = [
    "You absolute fungible token.",
    "You're the gas fee nobody wants to pay.",
    "Sir, this is a DeFi protocol, not a therapy session.",
    "Your wallet address is more trustworthy than your opinions.",
    "You're as liquid as a locked vesting schedule.",
    "Cope harder, ser.",
    "Ngmi. But in a charming way.",
    "You'd rugged yourself in a solo game.",
    "Your alpha is older than your conviction.",
    "Even the bears think you're too bearish.",
    "You're the slippage nobody accounts for.",
    "Mate, your risk tolerance is a liability.",
    "You sold the bottom. Again.",
    "Absolute goblin-mode energy.",
    "Your bonding curve goes straight down.",
    "Paper hands spotted. Incredible.",
    "You're the rebase nobody asked for.",
    "Fren, you're an impermanent loss walking.",
    "Your portfolio looks like a rug pull chart.",
    "You're the 'dev doxxed' of people — not reassuring.",
    "Sir, put down the leverage.",
    "You bought the top and called it 'early'.",
    "You're a governance proposal that never passed.",
    "Absolute smoothbrain move.",
    "Your DD is a Discord screenshot from 2021.",
    "You're a sybil attack on common sense.",
    "Certified bagholder energy.",
    "You're the sandwich bot nobody detected.",
    "Exit liquidity? No thanks, that's your job.",
    "You're what happens when FOMO has a baby with FUD.",
    "Absolutely rekt in the politest possible way.",
    "You couldn't find alpha in a yield farm.",
    "You're the 'one more dip' guy. Every time.",
    "You'd sell a RIZE bond at 3% maturity.",
    "Your conviction expires faster than a flash loan.",
    "You're more volatile than a 100x meme coin.",
    "Did you just market buy? Ser.",
    "You're the 'just 5 more minutes' of crypto investors.",
    "Absolutely meatbrained thesis.",
    "You're the phishing link in the group chat.",
    "Your tokenomics understanding is NFT-level.",
    "Sir, that's not alpha, that's cope.",
    "You're a rug pull waiting to happen.",
    "Your DAO governance vote doesn't count.",
    "Confirmed: you bought based on vibes.",
    "You're the impermanent in impermanent loss.",
    "Even the liquidity pool wants you out.",
    "Your analysis: line go up because number go up.",
    "You're what a panic sell looks like IRL.",
    "Certified exit liquidity. Touch grass.",
    "You're the kind of person who calls 20% a 'correction'.",
    "Your yield strategy is called hope.",
    "You bridged to the wrong chain, didn't you.",
    "Anon, your entry point is a cry for help.",
    "You market-sold into a sandwich attack. Impressive.",
    "Bro called it a 'dip' on the way down from -90%.",
    "Your LP position is just a donation with extra steps.",
    "You're not early, you're just wrong.",
    "That's not a thesis, that's a horoscope.",
    "You aped in and called it research.",
    "Your stop-loss is 'I'll sell when it recovers'.",
    "Ser, your conviction is inversely correlated with your net worth.",
    "You screenshot the green candle but not the wick.",
    "You're the reason liquidity pools need safety warnings.",
    "You told everyone to buy right before the dump. Thanks for the service.",
    "Your portfolio is a cautionary tale they'll teach in business school.",
    "You have the timing of a governance proposal on voting day.",
    "You called the bottom seven times. It wasn't any of them.",
    "Your DMs are full of 'I told you so' from yourself.",
    "You're not diamond hands, you're just frozen with fear.",
    "Your on-chain activity is a crime scene investigation.",
    "You've never held a position long enough to get a maturity boost.",
    "You're the reason we have 'do your own research' disclaimers.",
    "You sold to buy a meme coin. We don't forgive. We don't forget.",
    "Your idea of fundamental analysis is checking Twitter.",
    "Fren, your wallet history looks like abstract art.",
    "You're the 'ser wen pump' in every governance chat.",
    "You asked if RIZE was on Robinhood. Unforgivable.",
    "Your bonding strategy is 'whatever feels right'.",
    "You're the smart money that's always wrong.",
    "You called it a 'strategic accumulation zone'. It was a crash.",
    "You've got the patience of a flash loan.",
    "Your favourite technical indicator is vibes.",
    "You bought the rumour and the news and both dumps.",
    "You're the one who sells to fund the next person's gains.",
    "Liquidated twice in one week. Respect for the consistency.",
    "You think 'locked liquidity' means safe. Adorable.",
    "Your thesis aged like milk in August.",
    "You asked 'is this a good time to buy?' at the exact wrong moment. Always.",
    "You're still waiting for the 'confirmed reversal'. It's been 18 months.",
    "Your conviction is measured in hours.",
    "You treat red candles like they're optional.",
    "Ser, that's not a dip, that's a cliff.",
    "You're the maximum pain destination for every options trader.",
    "You sold your RIZE to buy something 'with more utility'. Tragic.",
    "Your entry was at resistance. Your exit was at support. Classic.",
    "You participated in 3 IDOs and lost money on all of them. Talent.",
    "You're the reason smart contracts need failsafes.",
    "Your wallet is a history of good intentions and terrible execution.",
    "You treat every red day like it's a black swan.",
    "Anon, your position sizing is a cry for help.",
    "You're not holding, you're coping.",
    "Even the mempool rejected your transaction. Eventually.",
    "You discovered RIZE and still haven't bonded. Unbelievable.",
    "You're what happens when confirmation bias meets leverage.",
    "Your 'long-term vision' is three days.",
    "You called the top a floor. Twice.",
    "Your roadmap is 'buy, panic, sell, repeat'.",
    "You think 5% APY is impressive. Ser.",
    "You broke your own stop-loss because you 'had a feeling'.",
    "You asked what DAML stands for. And then forgot.",
    "Your due diligence was a YouTube video from 2022.",
    "You're the one who FUDs at the bottom and hypes at the top.",
    "You're not a contrarian, you're just wrong on the other side.",
    "You bought the FOMO and sold the FUD. Congrats.",
    "You're the cautionary tale they didn't have time to include in the whitepaper.",
    "Your conviction is directly proportional to green candles.",
    "Anon, you have the analytical depth of a price ticker.",
    "You thought the vesting cliff was a metaphor.",
    "Your portfolio is balanced: 50% red, 50% more red.",
    "You're the 'sell wall' in human form.",
    "You've never read a tokenomics doc voluntarily. And it shows.",
    "You treat whitepapers like terms of service. Just scroll and click agree.",
    "You're the governance abstention in every vote.",
    "Your technical analysis chart looks like a Rorschach test.",
    "You described your losses as 'unrealized gains in reverse'.",
    "Even your hardware wallet is judging you.",
    "You said 'this time is different' and it wasn't.",
    "You're the bridge hack that was predicted six months in advance.",
    "Your staking rewards barely cover your gas fees. Somehow.",
    "You panic-sold and bought back 20% higher. Twice in one week.",
    "Your inner monologue during a dip is a horror movie.",
    "You're not a whale, you're a very confident shrimp.",
    "You've been 'waiting for confirmation' since Q2 2024.",
    "Your market timing is aggressively, consistently wrong.",
    "You're the permabull in a bear market and permabear in a bull market.",
    "Anon, your portfolio is held together by hopium and vibes.",
    "You've had five 'final' entries on the way down.",
    "You treat TVL like it's the same as revenue. Concerning.",
    "Your 'risk management strategy' is prayer.",
    "You argued with the protocol. The protocol won.",
    "You're the wallet address nobody wants to follow on-chain.",
    "Your conviction lasted until the first -5% candle.",
    "You staked at the top and unstaked at the bottom. Flawless.",
    "You're the reason DeFi protocols have big red warning banners.",
    "Your token picks have a 100% success rate at failure.",
    "You said 'fundamentals don't matter' in a bull market. Then they did.",
    "You're the 'just a few more weeks' in every delayed project.",
    "Your favourite exit strategy is 'it'll come back'.",
    "You're the one who tips off the front-runners without knowing it.",
    "Anon, your risk/reward ratio is a tragedy.",
    "You've been averaging down since before averaging down was a meme.",
    "You're the 'I meant to do that' of on-chain actors.",
    "Your version of hodl is just forgetting your seed phrase.",
    "You called it 'accumulation'. The chart called it 'bleeding'.",
    "You're the governance voter who abstains on every critical proposal.",
    "Your on-chain journey reads like a loss porn subreddit thread.",
    "You trade like you're running a study on how much pain a human can endure.",
    "You're the impermanent loss that became permanent.",
    "Anon, your token research process is literally vibes.",
    "You thought 'liquidity' meant your own wallet was liquid. It wasn't.",
    "Your FOMO is so strong it has its own gravitational field.",
    "You're the kind of user that liquidity protocols pray don't show up.",
    "You called it a 'consolidation phase'. It was a collapse.",
    "You're the smart contract vulnerability no one audited for.",
    "Your conviction is the blockchain equivalent of a verbal agreement.",
    "You're not an early adopter, you're an early capitulator.",
    "Even your stop-losses have stop-losses.",
    "You bought the narrative before reading the docs. Naturally.",
    "You're the user who causes gas to spike for everyone else.",
    "Your portfolio looks like a governance proposal that got 4% votes.",
    "You hold until it's worthless, then sell. Every single time.",
    "You thought you understood the tokenomics. The vesting cliff says hello.",
    "Your definition of 'research' is asking in a Telegram group.",
    "You're a cautionary tale in a market full of cautionary tales.",
    "You're the 'I'm fine' while portfolio is -80%.",
    "Your market commentary is wrong so consistently it's almost useful as a reverse indicator.",
    "You have more conviction about things you know nothing about than things you've studied.",
    "Anon, the only thing maturing in your portfolio is the hopium.",
    "You're the reason the 'are you sure?' confirmation dialog exists.",
]


async def cmd_sayhello(args: list) -> str:
    return random.choice(GREETINGS)


async def cmd_insult(args: list) -> str:
    return f"🔥 {random.choice(INSULTS)}"
